// Generated by Hebron at 10/14/2025 5:34:22 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace MikkTSpaceSharp
{
	unsafe partial class MikkTSpace
	{
		public unsafe class SMikkTSpaceContext
		{
			public getNumFacesDelegate m_getNumFaces;
			public getNumVerticesOfFaceDelegate m_getNumVerticesOfFace;
			public getPositionDelegate m_getPosition;
			public getPositionDelegate m_getNormal;
			public getTexCoordDelegate m_getTexCoord;
			public setTSpaceBasicDelegate m_setTSpaceBasic;
			public setTSpaceDelegate m_setTSpace;
		}

		public struct SVec2
		{
			public float x;
			public float y;

			public SVec2(float xx, float yy)
			{
				x = xx;
				y = yy;
			}
		}

		public struct SVec3
		{
			public float x;
			public float y;
			public float z;

			public SVec3(float xx, float yy, float zz)
			{
				x = xx;
				y = yy;
				z = zz;
			}
		}

		public unsafe struct SSubGroup
		{
			public int iNrFaces;
			public int* pTriMembers;
		}

		public unsafe struct SGroup
		{
			public int iNrFaces;
			public int* pFaceIndices;
			public int iVertexRepresentitive;
			public int bOrientPreservering;
		}

		public unsafe class STriInfo
		{
			public int[] FaceNeighbors = new int[3];
			public SGroup*[] AssignedGroup = new SGroup*[3];
			public SVec3 vOs;
			public SVec3 vOt;
			public float fMagS;
			public float fMagT;
			public int iOrgFaceNumber;
			public int iFlag;
			public int iTSpacesOffs;
			public byte[] vert_num = new byte[4];
		}

		public struct STSpace
		{
			public SVec3 vOs;
			public float fMagS;
			public SVec3 vOt;
			public float fMagT;
			public int iCounter;
			public int bOrient;
		}

		public unsafe struct STmpVert
		{
			public fixed float vert[3];
			public int index;
		}
	}
}