// Generated by Hebron at 10/14/2025 5:34:22 AM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace MikkTSpaceSharp
{
	unsafe partial class MikkTSpace
	{
		public unsafe class SMikkTSpaceContext
		{
			public SMikkTSpaceInterface m_pInterface;
			public void* m_pUserData;
		}

		public class SMikkTSpaceInterface
		{
			public delegate0 m_getNumFaces;
			public delegate1 m_getNumVerticesOfFace;
			public delegate2 m_getPosition;
			public delegate2 m_getNormal;
			public delegate2 m_getTexCoord;
			public delegate3 m_setTSpaceBasic;
			public delegate4 m_setTSpace;
		}

		public struct SVec3
		{
			public float x;
			public float y;
			public float z;
		}

		public unsafe struct SSubGroup
		{
			public int iNrFaces;
			public int* pTriMembers;
		}

		public unsafe struct SGroup
		{
			public int iNrFaces;
			public int* pFaceIndices;
			public int iVertexRepresentitive;
			public int bOrientPreservering;
		}

		public unsafe class STriInfo
		{
			public int[] FaceNeighbors = new int[3];
			public SGroup*[] AssignedGroup = new SGroup*[3];
			public SVec3 vOs;
			public SVec3 vOt;
			public float fMagS;
			public float fMagT;
			public int iOrgFaceNumber;
			public int iFlag;
			public int iTSpacesOffs;
			public byte[] vert_num = new byte[4];
		}

		public struct STSpace
		{
			public SVec3 vOs;
			public float fMagS;
			public SVec3 vOt;
			public float fMagT;
			public int iCounter;
			public int bOrient;
		}

		public unsafe struct STmpVert
		{
			public fixed float vert[3];
			public int index;
		}
	}
}